const HELP_DATA = {
  "principalpage": {
    titulo: { es: "¡Bienvenido a Let's Go Catbling!", en: "Welcome to Let's Go Catbling!", ru: "Добро пожаловать в Let's Go Catbling!", ja: "Let's Go Catblingへようこそ！", zh: "欢迎来到 Let's Go Catbling！", de: "Willkommen bei Let's Go Catbling!" },
    secciones: [
      { titulo: { es: "Pantalla Principal", en: "Main Screen", ru: "Главный экран", ja: "メイン画面", zh: "主屏幕", de: "Hauptbildschirm" }, contenido: { es: "Aquí puedes ir a las 3 partes del juego: Preguntas, Casino y Tienda. Usa el menú (⚙️) para cambiar música, sonidos y más.", en: "Here you can go to the 3 parts of the game: Questions, Casino and Shop. Use the menu (⚙️) to change music, sounds and more.", ru: "Здесь вы можете перейти к 3 разделам игры: Вопросы, Казино и Магазин. Используйте меню (⚙️), чтобы изменить музыку, звуки и другое.", ja: "ここではゲームの3つのパート（クイズ、カジノ、ショップ）に移動できます。メニュー（⚙️）で音楽やサウンドなどを変更できます。", zh: "在这里你可以进入游戏的3个部分：问答、赌场和商店。使用菜单（⚙️）更改音乐、音效等设置。", de: "Hier gelangst du zu den 3 Teilen des Spiels: Fragen, Casino und Shop. Nutze das Menü (⚙️), um Musik, Sounds und mehr zu ändern." }, icono: "🏠" },
      { titulo: { es: "Monedas", en: "Coins", ru: "Монеты", ja: "コイン", zh: "金币", de: "Münzen" }, contenido: { es: "Las monedas sirven para jugar. Puedes ganar monedas respondiendo preguntas o jugando en el casino. Si no tienes monedas, recibirás 10 gratis después de un rato.", en: "Coins are the game currency. You can earn coins by answering questions or playing in the casino. If you run out of coins, you'll get 10 free after a while.", ru: "Монеты нужны, чтобы играть. Вы можете зарабатывать монеты, отвечая на вопросы или играя в казино. Если у вас закончились монеты, вы получите 10 бесплатно через некоторое время.", ja: "コインはプレイに必要です。クイズに答えたりカジノで遊んだりしてコインを稼げます。コインがなくなっても、しばらくすると10枚無料でもらえます。", zh: "金币是游戏中的货币。你可以通过回答问题或在赌场游戏来赚取金币。如果金币用完了，过一会儿会免费获得10枚。", de: "Münzen brauchst du zum Spielen. Du kannst Münzen verdienen, indem du Fragen beantwortest oder im Casino spielst. Gehen dir die Münzen aus, bekommst du nach einer Weile 10 gratis." }, icono: "🪙" },
      { titulo: { es: "Sección Preguntas", en: "Questions Section", ru: "Раздел «Вопросы»", ja: "クイズセクション", zh: "问答版块", de: "Fragen-Bereich" }, contenido: { es: "Elige un tema y una dificultad. Responde bien las preguntas para ganar monedas. Si eliges difícil, ganarás más monedas.", en: "Choose a topic and difficulty. Answer questions correctly to earn coins. Harder difficulty gives more coins.", ru: "Выберите тему и сложность. Правильно отвечайте на вопросы, чтобы зарабатывать монеты. Если выберете сложный уровень, заработаете больше монет.", ja: "テーマと難易度を選んでください。正しく答えるとコインがもらえます。難しい方を選ぶほど多くのコインが手に入ります。", zh: "选择一个主题和难度。正确回答问题即可获得金币，难度越高，获得的金币越多。", de: "Wähle ein Thema und einen Schwierigkeitsgrad. Beantworte die Fragen richtig, um Münzen zu verdienen. Bei höherem Schwierigkeitsgrad bekommst du mehr Münzen." }, icono: "❓" },
      { titulo: { es: "Sección Casino", en: "Casino Section", ru: "Раздел «Казино»", ja: "カジノセクション", zh: "赌场版块", de: "Casino-Bereich" }, contenido: { es: "En el casino hay varios juegos: Tragamonedas, Memoria, Duelo de Dados, Ruleta y Jackpot de Dados. Cada juego tiene sus propias reglas y premios.", en: "The casino has several games: Slots, Memory, Dice Duel, Roulette and Dice Jackpot. Each game has its own rules and prizes.", ru: "В казино есть несколько игр: Игровой автомат, Память, Дуэль на костях, Рулетка и Джекпот костей. У каждой игры свои правила и призы.", ja: "カジノにはスロット、メモリー、サイコロ対決、ルーレット、サイコロジャックポットなど、いくつかのゲームがあります。ゲームごとにルールと賞品が異なります。", zh: "赌场里有多种游戏：老虎机、记忆翻牌、骰子对决、轮盘和骰子累积奖池。每种游戏都有各自的规则和奖励。", de: "Im Casino gibt es mehrere Spiele: Spielautomat, Memory, Würfelduell, Roulette und Würfel-Jackpot. Jedes Spiel hat eigene Regeln und Preise." }, icono: "🎰" },
      { titulo: { es: "Tienda", en: "Shop", ru: "Магазин", ja: "ショップ", zh: "商店", de: "Shop" }, contenido: { es: "Gasta tus monedas en mejoras para las preguntas, ayudas para el casino y accesorios. Los objetos se guardan en tu bolsa.", en: "Spend your coins on question upgrades, casino power-ups and accessories. Items are saved in your bag.", ru: "Тратьте монеты на улучшения для вопросов, усиления для казино и аксессуары. Предметы сохраняются в вашей сумке.", ja: "コインを使って、クイズ用のアップグレード、カジノ用のパワーアップ、アクセサリーを購入できます。アイテムはバッグに保存されます。", zh: "花费金币购买问答升级道具、赌场辅助道具和装饰品。购买的物品会保存在你的背包中。", de: "Gib deine Münzen für Frage-Upgrades, Casino-Power-ups und Accessoires aus. Gegenstände werden in deiner Tasche gespeichert." }, icono: "🛒" }
    ]
  },
  "juegos": {
    titulo: { es: "Casino - Elige un Juego", en: "Casino - Choose a Game", ru: "Казино — выберите игру", ja: "カジノ - ゲームを選ぶ", zh: "赌场 - 选择一款游戏", de: "Casino - Wähle ein Spiel" },
    secciones: [
      { titulo: { es: "Navegación", en: "Navigation", ru: "Навигация", ja: "ナビゲーション", zh: "导航", de: "Navigation" }, contenido: { es: "Usa las flechas para moverte entre los juegos. Haz clic en la imagen o presiona Enter para entrar al juego. También puedes usar las teclas A/D o las flechas del teclado.", en: "Use the arrows to move between games. Click the image or press Enter to enter the game. You can also use A/D keys or arrow keys.", ru: "Используйте стрелки, чтобы переключаться между играми. Нажмите на изображение или Enter, чтобы войти в игру. Также можно использовать клавиши A/D или стрелки клавиатуры.", ja: "矢印を使ってゲームを切り替えましょう。画像をクリックするかEnterキーでゲームに入れます。A/Dキーや矢印キーも使用できます。", zh: "使用箭头在游戏间切换。点击图片或按Enter键进入游戏，也可以使用A/D键或方向键。", de: "Nutze die Pfeile, um zwischen den Spielen zu wechseln. Klicke auf das Bild oder drücke Enter, um das Spiel zu starten. Du kannst auch die Tasten A/D oder die Pfeiltasten benutzen." }, icono: "🎮" },
      { titulo: { es: "Tragamonedas", en: "Slots", ru: "Игровой автомат", ja: "スロット", zh: "老虎机", de: "Spielautomat" }, contenido: { es: "Gira los rodillos y consigue 3 símbolos iguales para ganar. Apuesta mínimo 10 monedas. Si aciertas, multiplicas tu apuesta por 50.", en: "Spin the reels and get 3 matching symbols to win. Minimum bet is 10 coins. If you win, you multiply your bet by 50.", ru: "Крутите барабаны и соберите 3 одинаковых символа, чтобы выиграть. Минимальная ставка — 10 монет. Если угадаете, ваша ставка умножается на 50.", ja: "リールを回して同じ絵柄を3つ揃えると勝利です。最低ベット額は10コイン。勝てばベット額が50倍になります。", zh: "转动转轮，凑出3个相同图案即可获胜。最低赌注为10枚金币。获胜后赌注会乘以50倍。", de: "Dreh die Walzen und erziele 3 gleiche Symbole, um zu gewinnen. Mindesteinsatz ist 10 Münzen. Bei einem Gewinn wird dein Einsatz mit 50 multipliziert." }, icono: "🎰" },
      { titulo: { es: "Memoria", en: "Memory", ru: "Память", ja: "メモリー", zh: "记忆翻牌", de: "Memory" }, contenido: { es: "Encuentra los pares de cartas iguales. Completa todos los pares en pocos movimientos para ganar el doble de tu apuesta. Apuesta desde 7 monedas.", en: "Find the matching card pairs. Complete all pairs in few moves to win double your bet. Bet from 7 coins.", ru: "Найдите одинаковые пары карт. Соберите все пары за несколько ходов, чтобы выиграть удвоенную ставку. Ставка начинается от 7 монет.", ja: "同じ絵柄のカードのペアを見つけましょう。少ない手数ですべてのペアを揃えるとベット額の2倍を獲得できます。ベット額は7コインから。", zh: "找出相同的配对卡牌。用较少的步数完成所有配对即可赢得双倍赌注。赌注最低为7枚金币。", de: "Finde die passenden Kartenpaare. Vervollständige alle Paare in wenigen Zügen, um das Doppelte deines Einsatzes zu gewinnen. Einsatz ab 7 Münzen." }, icono: "🧠" },
      { titulo: { es: "Duelo de Dados", en: "Dice Duel", ru: "Дуэль на костях", ja: "サイコロ対決", zh: "骰子对决", de: "Würfelduell" }, contenido: { es: "Lanza 2 dados. Ganas si: salen iguales (x4), son seguidos (x3), o los dos son pares (x2). Apuesta fija de 5 monedas.", en: "Roll 2 dice. You win if: they match (x4), they are consecutive (x3), or both are even (x2). Fixed bet of 5 coins.", ru: "Бросьте 2 кубика. Вы побеждаете, если: выпали одинаковые числа (x4), числа идут подряд (x3), или оба числа чётные (x2). Фиксированная ставка — 5 монет.", ja: "2つのサイコロを振ります。出目が同じ（x4）、連続した数字（x3）、両方偶数（x2）のいずれかで勝利です。ベット額は5コイン固定。", zh: "掷出2颗骰子。若点数相同（x4）、点数连续（x3）或两个都是偶数（x2）即可获胜。固定赌注为5枚金币。", de: "Würfle mit 2 Würfeln. Du gewinnst, wenn: beide gleich sind (x4), sie aufeinanderfolgen (x3) oder beide gerade sind (x2). Fester Einsatz von 5 Münzen." }, icono: "🎲" },
      { titulo: { es: "Ruleta", en: "Roulette", ru: "Рулетка", ja: "ルーレット", zh: "轮盘", de: "Roulette" }, contenido: { es: "Apunta a números, columnas o colores. Gira la ruleta: número exacto (35x), columna (2x) o color (1x).", en: "Bet on numbers, columns or colors. Spin the wheel: exact number (35x), column (2x) or color (1x).", ru: "Делайте ставки на числа, колонки или цвета. Крутите рулетку: точное число (35x), колонка (2x) или цвет (1x).", ja: "数字、列、色に賭けましょう。ルーレットを回すと、数字的中は35倍、列は2倍、色は1倍の配当です。", zh: "押注数字、列或颜色。转动轮盘：猜中确切数字得35倍，列得2倍，颜色得1倍。", de: "Setze auf Zahlen, Kolonnen oder Farben. Dreh das Rad: genaue Zahl (35x), Kolonne (2x) oder Farbe (1x)." }, icono: "🎡" },
      { titulo: { es: "Jackpot de Dados", en: "Dice Jackpot", ru: "Джекпот костей", ja: "サイコロジャックポット", zh: "骰子累积奖池", de: "Würfel-Jackpot" }, contenido: { es: "Parecido al Duelo de Dados pero puedes elegir cuánto apostar. Apuesta mínimo 10. Gana con pares, números seguidos o pares iguales.", en: "Similar to Dice Duel but you can choose your bet. Minimum bet 10. Win with pairs, consecutive numbers or both even.", ru: "Похоже на Дуэль на костях, но вы сами выбираете сумму ставки. Минимальная ставка — 10. Побеждайте с парами, последовательными числами или двумя чётными числами.", ja: "サイコロ対決に似ていますが、ベット額を自分で選べます。最低ベット額は10。ペア、連続した数字、両方偶数のいずれかで勝利です。", zh: "类似骰子对决，但你可以自行选择赌注。最低赌注为10。凑成对子、连续数字或两个偶数即可获胜。", de: "Ähnlich wie Würfelduell, aber du kannst deinen Einsatz wählen. Mindesteinsatz 10. Gewinne mit Paaren, aufeinanderfolgenden Zahlen oder zwei geraden Zahlen." }, icono: "🎲" }
    ]
  },
  "preguntas": {
    titulo: { es: "Sección de Preguntas", en: "Questions Section", ru: "Раздел «Вопросы»", ja: "クイズセクション", zh: "问答版块", de: "Fragen-Bereich" },
    secciones: [
      { titulo: { es: "Cómo jugar", en: "How to play", ru: "Как играть", ja: "遊び方", zh: "玩法", de: "Spielanleitung" }, contenido: { es: "1. Elige un tema (botones de colores).\n2. Escoge la dificultad con las flechas.\n3. Responde las preguntas.\n4. Gana monedas por cada respuesta correcta.", en: "1. Choose a topic (colored buttons).\n2. Pick difficulty with the arrows.\n3. Answer the questions.\n4. Earn coins for each correct answer.", ru: "1. Выберите тему (цветные кнопки).\\n2. Выберите сложность с помощью стрелок.\\n3. Отвечайте на вопросы.\\n4. Зарабатывайте монеты за каждый правильный ответ.", ja: "1. テーマを選ぶ（カラーボタン）。\\n2. 矢印で難易度を選ぶ。\\n3. 質問に答える。\\n4. 正解ごとにコインを獲得。", zh: "1. 选择一个主题（彩色按钮）。\\n2. 用箭头选择难度。\\n3. 回答问题。\\n4. 每答对一题即可获得金币。", de: "1. Wähle ein Thema (farbige Buttons).\\n2. Wähle die Schwierigkeit mit den Pfeilen.\\n3. Beantworte die Fragen.\\n4. Verdiene Münzen für jede richtige Antwort." }, icono: "📖" },
      { titulo: { es: "Áreas de Conocimiento", en: "Knowledge Areas", ru: "Области знаний", ja: "知識分野", zh: "知识领域", de: "Wissensbereiche" }, contenido: { es: "Cada botón de color es un tema diferente: Ciencias, Historia, Matemáticas, Geografía, Deportes, Entretenimiento.", en: "Each colored button is a different topic: Science, History, Math, Geography, Sports, Entertainment.", ru: "Каждая цветная кнопка — это отдельная тема: Наука, История, Математика, География, Спорт, Развлечения.", ja: "各カラーボタンは異なるテーマを表します：科学、歴史、数学、地理、スポーツ、エンターテインメント。", zh: "每个彩色按钮代表一个不同的主题：科学、历史、数学、地理、体育、娱乐。", de: "Jeder farbige Button steht für ein anderes Thema: Wissenschaft, Geschichte, Mathematik, Geografie, Sport, Unterhaltung." }, icono: "🎯" },
      { titulo: { es: "Dificultad", en: "Difficulty", ru: "Сложность", ja: "難易度", zh: "难度", de: "Schwierigkeit" }, contenido: { es: "Fácil: preguntas sencillas, pocas monedas.\nMedio: un poco más difícil, mejores premios.\nDifícil: preguntas difíciles, grandes recompensas.", en: "Easy: simple questions, few coins.\nMedium: a bit harder, better prizes.\nHard: hard questions, big rewards.", ru: "Лёгкий: простые вопросы, мало монет.\\nСредний: чуть сложнее, лучшие призы.\\nСложный: трудные вопросы, большие награды.", ja: "簡単：シンプルな質問、少ないコイン。\\n普通：少し難しい、より良い報酬。\\n難しい：難しい質問、大きな報酬。", zh: "简单：题目简单，金币较少。\\n中等：稍有难度，奖励更好。\\n困难：题目较难，奖励丰厚。", de: "Leicht: einfache Fragen, wenige Münzen.\\nMittel: etwas schwieriger, bessere Preise.\\nSchwer: schwierige Fragen, große Belohnungen." }, icono: "📊" },
      { titulo: { es: "Recompensas", en: "Rewards", ru: "Награды", ja: "報酬", zh: "奖励", de: "Belohnungen" }, contenido: { es: "Cada respuesta correcta te da monedas. A mayor dificultad, más monedas ganarás.", en: "Each correct answer gives you coins. The harder the difficulty, the more coins you earn.", ru: "Каждый правильный ответ приносит монеты. Чем выше сложность, тем больше монет вы заработаете.", ja: "正解するたびにコインがもらえます。難易度が高いほど、獲得できるコインも増えます。", zh: "每答对一题都会获得金币，难度越高，获得的金币越多。", de: "Jede richtige Antwort bringt dir Münzen. Je höher die Schwierigkeit, desto mehr Münzen verdienst du." }, icono: "🏆" }
    ]
  },
  "tienda": {
    titulo: { es: "Tienda de Objetos", en: "Item Shop", ru: "Магазин предметов", ja: "アイテムショップ", zh: "物品商店", de: "Gegenstands-Shop" },
    secciones: [
      { titulo: { es: "Categorías", en: "Categories", ru: "Категории", ja: "カテゴリー", zh: "分类", de: "Kategorien" }, contenido: { es: "Preguntas: mejoras para ayudarte.\nCasino: ayudas para los juegos.\nAccesorios: objetos para decorar (pronto).", en: "Questions: upgrades to help you.\nCasino: power-ups for games.\nAccessories: decorative items (coming soon).", ru: "Вопросы: улучшения, которые вам помогут.\\nКазино: усиления для игр.\\nАксессуары: декоративные предметы (скоро).", ja: "クイズ：あなたを助けるアップグレード。\\nカジノ：ゲーム用のパワーアップ。\\nアクセサリー：装飾アイテム（近日公開）。", zh: "问答：帮助你的升级道具。\\n赌场：游戏辅助道具。\\n装饰品：装饰性物品（即将推出）。", de: "Fragen: Upgrades, die dir helfen.\\nCasino: Power-ups für Spiele.\\nAccessoires: Deko-Gegenstände (demnächst)." }, icono: "🏪" },
      { titulo: { es: "Cómo comprar", en: "How to buy", ru: "Как покупать", ja: "購入方法", zh: "购买方法", de: "So kaufst du" }, contenido: { es: "Elige una categoría, navega con las flechas y haz clic en COMPRAR. Puedes tener hasta 3 objetos en tu bolsa.", en: "Choose a category, navigate with arrows and click BUY. You can have up to 3 items in your bag.", ru: "Выберите категорию, перемещайтесь стрелками и нажмите КУПИТЬ. В сумке может быть до 3 предметов.", ja: "カテゴリーを選び、矢印で移動して「購入」をクリックしましょう。バッグには最大3個のアイテムを持てます。", zh: "选择一个分类，用箭头浏览，然后点击“购买”。你的背包最多可容纳3件物品。", de: "Wähle eine Kategorie, navigiere mit den Pfeilen und klicke auf KAUFEN. Du kannst bis zu 3 Gegenstände in deiner Tasche haben." }, icono: "🛍️" },
      { titulo: { es: "Usar objetos", en: "Use items", ru: "Использование предметов", ja: "アイテムの使用", zh: "使用物品", de: "Gegenstände benutzen" }, contenido: { es: "Ve a tu bolsa (icono de bolsa), elige un objeto y confirma para usarlo. Las mejoras se activan solas.", en: "Go to your bag (bag icon), select an item and confirm to use it. Upgrades activate automatically.", ru: "Перейдите в свою сумку (значок сумки), выберите предмет и подтвердите использование. Улучшения активируются автоматически.", ja: "バッグ（バッグアイコン）に移動し、アイテムを選んで使用を確定してください。アップグレードは自動的に発動します。", zh: "前往你的背包（背包图标），选择一个物品并确认使用。升级道具会自动生效。", de: "Geh zu deiner Tasche (Taschensymbol), wähle einen Gegenstand aus und bestätige die Nutzung. Upgrades aktivieren sich automatisch." }, icono: "🎒" },
      { titulo: { es: "Monedas", en: "Coins", ru: "Монеты", ja: "コイン", zh: "金币", de: "Münzen" }, contenido: { es: "Revisa tus monedas en la esquina de arriba a la derecha. Si no tienes suficientes, juega a preguntas o al casino para ganar más.", en: "Check your coins in the top right corner. If you don't have enough, play questions or casino to earn more.", ru: "Проверьте свои монеты в правом верхнем углу. Если их не хватает, играйте в вопросы или казино, чтобы заработать больше.", ja: "画面右上でコインを確認できます。足りない場合は、クイズやカジノでプレイして稼ぎましょう。", zh: "在右上角查看你的金币数量。如果不够，可以去问答或赌场赚取更多。", de: "Überprüfe deine Münzen oben rechts. Wenn du nicht genug hast, spiele Fragen oder Casino, um mehr zu verdienen." }, icono: "💰" }
    ]
  },
  "tragamonedas": {
    titulo: { es: "Tragamonedas - Cómo jugar", en: "Slots - How to play", ru: "Игровой автомат — как играть", ja: "スロット - 遊び方", zh: "老虎机 - 玩法", de: "Spielautomat - Spielanleitung" },
    secciones: [
      { titulo: { es: "Objetivo", en: "Goal", ru: "Цель", ja: "目的", zh: "目标", de: "Ziel" }, contenido: { es: "Consigue que los 3 rodillos muestren el mismo símbolo para ganar el premio mayor.", en: "Get all 3 reels to show the same symbol to win the jackpot.", ru: "Получите одинаковый символ на всех 3 барабанах, чтобы выиграть главный приз.", ja: "3つのリールすべてに同じ絵柄を揃えると、ジャックポットを獲得できます。", zh: "让3个转轮都显示相同的图案，即可赢得大奖。", de: "Erziele auf allen 3 Walzen dasselbe Symbol, um den Jackpot zu gewinnen." }, icono: "🎯" },
      { titulo: { es: "Apuesta", en: "Bet", ru: "Ставка", ja: "ベット", zh: "赌注", de: "Einsatz" }, contenido: { es: "Usa el control deslizante para elegir tu apuesta (mínimo 10, máximo 500 monedas).", en: "Use the slider to choose your bet (minimum 10, maximum 500 coins).", ru: "Используйте ползунок, чтобы выбрать ставку (минимум 10, максимум 500 монет).", ja: "スライダーを使ってベット額を選びましょう（最低10、最高500コイン）。", zh: "使用滑块选择你的赌注（最低10枚，最高500枚金币）。", de: "Nutze den Schieberegler, um deinen Einsatz zu wählen (mindestens 10, maximal 500 Münzen)." }, icono: "💰" },
      { titulo: { es: "Premios", en: "Prizes", ru: "Призы", ja: "賞品", zh: "奖励", de: "Preise" }, contenido: { es: "Si los 3 símbolos son iguales, ganas tu apuesta x 50. ¡Gran premio!", en: "If all 3 symbols match, you win your bet x 50. Big prize!", ru: "Если все 3 символа совпадают, вы выигрываете свою ставку x 50. Отличный приз!", ja: "3つの絵柄が揃えば、ベット額の50倍を獲得！大当たりです！", zh: "如果3个图案都相同，你将赢得赌注的50倍！超级大奖！", de: "Wenn alle 3 Symbole übereinstimmen, gewinnst du das 50-fache deines Einsatzes. Großer Gewinn!" }, icono: "🏆" },
      { titulo: { es: "Controles", en: "Controls", ru: "Управление", ja: "操作方法", zh: "操作方式", de: "Steuerung" }, contenido: { es: "Haz clic en el botón rojo GIRAR o presiona Enter/Espacio para girar.", en: "Click the red SPIN button or press Enter/Space to spin.", ru: "Нажмите на красную кнопку КРУТИТЬ или используйте Enter/Пробел, чтобы вращать.", ja: "赤い「回す」ボタンをクリックするか、Enter/スペースキーで回転させましょう。", zh: "点击红色的“旋转”按钮，或按Enter/空格键进行旋转。", de: "Klicke auf den roten DREHEN-Button oder drücke Enter/Leertaste zum Drehen." }, icono: "🎮" }
    ]
  },
  "memoria": {
    titulo: { es: "Memoria - Cómo jugar", en: "Memory - How to play", ru: "Память — как играть", ja: "メモリー - 遊び方", zh: "记忆翻牌 - 玩法", de: "Memory - Spielanleitung" },
    secciones: [
      { titulo: { es: "Objetivo", en: "Goal", ru: "Цель", ja: "目的", zh: "目标", de: "Ziel" }, contenido: { es: "Encuentra todos los pares de cartas iguales. Cada nivel tiene más pares.", en: "Find all matching card pairs. Each level has more pairs.", ru: "Найдите все одинаковые пары карт. С каждым уровнем пар становится больше.", ja: "同じカードのペアをすべて見つけましょう。レベルが上がるほどペア数が増えます。", zh: "找出所有相同的配对卡牌，关卡越高，配对数量越多。", de: "Finde alle passenden Kartenpaare. Mit jedem Level gibt es mehr Paare." }, icono: "🎯" },
      { titulo: { es: "Apuesta", en: "Bet", ru: "Ставка", ja: "ベット", zh: "赌注", de: "Einsatz" }, contenido: { es: "Elige tu apuesta (mínimo 7, máximo 500 monedas).", en: "Choose your bet (minimum 7, maximum 500 coins).", ru: "Выберите свою ставку (минимум 7, максимум 500 монет).", ja: "ベット額を選びましょう（最低7、最高500コイン）。", zh: "选择你的赌注（最低7枚，最高500枚金币）。", de: "Wähle deinen Einsatz (mindestens 7, maximal 500 Münzen)." }, icono: "💰" },
      { titulo: { es: "Ganar", en: "Win", ru: "Победа", ja: "勝利条件", zh: "获胜", de: "Gewinnen" }, contenido: { es: "Si completas todos los pares en los movimientos permitidos, ganas el premio. ¡Mientras más difícil el nivel, mayor el premio!", en: "If you complete all pairs within the allowed moves, you win the prize. The harder the level, the bigger the prize!", ru: "Если вы завершите все пары в пределах допустимых ходов, вы выиграете приз. Чем сложнее уровень, тем больше приз!", ja: "許容された手数以内にすべてのペアを揃えると賞品を獲得できます。レベルが難しいほど賞品も豪華に！", zh: "如果你在允许的步数内完成所有配对，就能赢得奖励。关卡越难，奖励越丰厚！", de: "Wenn du alle Paare innerhalb der erlaubten Züge findest, gewinnst du den Preis. Je schwieriger das Level, desto größer der Preis!" }, icono: "🏆" },
      { titulo: { es: "Consejos", en: "Tips", ru: "Советы", ja: "コツ", zh: "小贴士", de: "Tipps" }, contenido: { es: "Concéntrate y recuerda dónde está cada carta. A menos movimientos, más chances de ganar.", en: "Focus and remember where each card is. Fewer moves means more chances to win.", ru: "Сосредоточьтесь и запоминайте расположение карт. Чем меньше ходов, тем больше шансов на победу.", ja: "集中してカードの位置を覚えましょう。手数が少ないほど勝つ可能性が高まります。", zh: "集中注意力，记住每张卡牌的位置。步数越少，获胜机会越大。", de: "Konzentriere dich und merke dir, wo jede Karte liegt. Je weniger Züge, desto größer die Gewinnchance." }, icono: "💡" }
    ]
  },
  "ruleta": {
    titulo: { es: "✨ ¡La Ruleta Mágica! ✨", en: "✨ The Magic Roulette! ✨", ru: "✨ Волшебная рулетка! ✨", ja: "✨ 魔法のルーレット！ ✨", zh: "✨ 魔法轮盘！ ✨", de: "✨ Das magische Roulette! ✨" },
    secciones: [
      { titulo: { es: "🎯 ¿Cómo se juega?", en: "🎯 How to play?", ru: "🎯 Как играть?", ja: "🎯 遊び方は？", zh: "🎯 怎么玩？", de: "🎯 Wie spielt man?" }, contenido: { es: "Tienes que adivinar qué número va a salir. ¡Como un adivino pero con monedas! Puedes apostar a un solo número, a una columna entera o a un color.", en: "You have to guess which number will pop out! Like a fortune teller but with coins! You can bet on one number, a whole column, or a color.", ru: "Вам нужно угадать, какое число выпадет. Как гадалка, только с монетами! Можно поставить на одно число, целую колонку или цвет.", ja: "出てくる数字を当てましょう！占い師みたいだけどコイン付き！1つの数字、列全体、または色に賭けられます。", zh: "你需要猜出会出现哪个数字。就像算命一样，只是用金币代替！你可以押注单个数字、整列或颜色。", de: "Du musst erraten, welche Zahl herauskommt. Wie ein Wahrsager, nur mit Münzen! Du kannst auf eine Zahl, eine ganze Kolonne oder eine Farbe setzen." }, icono: "🎯" },
      { titulo: { es: "💰 ¿Cuánto puedes GANAR?", en: "💰 How much can you WIN?", ru: "💰 Сколько можно ВЫИГРАТЬ?", ja: "💰 いくら勝てるの？", zh: "💰 你能赢多少？", de: "💰 Wie viel kannst du GEWINNEN?" }, contenido: { es: "🎯 Un solo número → ¡35 veces tu apuesta! (¡millonario!)\n📊 Una columna (Col 1/2/3) → 2 veces tu apuesta\n🔴⚫ Un color (Rojo/Negro) → 1 vez tu apuesta\n👟 Entre más números marques, menos ganas pero más fácil le atinas.", en: "🎯 One number → 35 times your bet! (jackpot!)\n📊 A column (Col 1/2/3) → 2 times your bet\n🔴⚫ A color (Red/Black) → 1 times your bet\n👟 The more numbers you pick, the less you win but it's easier to hit!", ru: "🎯 Одно число → в 35 раз больше вашей ставки! (миллионер!)\\n📊 Колонка (Кол. 1/2/3) → в 2 раза больше ставки\\n🔴⚫ Цвет (Красный/Чёрный) → 1 раз ваша ставка\\n👟 Чем больше чисел вы отметите, тем меньше выигрыш, но тем легче попасть.", ja: "🎯 数字1つ→ベット額の35倍！（億万長者！）\\n📊 列（Col 1/2/3）→ベット額の2倍\\n🔴⚫ 色（赤/黒）→ベット額の1倍\\n👟 選ぶ数字が多いほど当てやすくなりますが、勝ち額は少なくなります。", zh: "🎯 单个数字 → 赌注的35倍！（一夜暴富！）\\n📊 一列（第1/2/3列）→ 赌注的2倍\\n🔴⚫ 一种颜色（红/黑）→ 赌注的1倍\\n👟 你标记的数字越多，赢得越少，但越容易猜中。", de: "🎯 Eine Zahl → das 35-fache deines Einsatzes! (Millionär!)\\n📊 Eine Kolonne (Kol. 1/2/3) → das 2-fache deines Einsatzes\\n🔴⚫ Eine Farbe (Rot/Schwarz) → das 1-fache deines Einsatzes\\n👟 Je mehr Zahlen du markierst, desto weniger gewinnst du, aber desto leichter triffst du." }, icono: "💰" },
      { titulo: { es: "🖱️ Cómo apostar paso a paso", en: "🖱️ How to bet step by step", ru: "🖱️ Как делать ставку шаг за шагом", ja: "🖱️ 賭け方をステップごとに解説", zh: "🖱️ 逐步下注指南", de: "🖱️ So wettest du Schritt für Schritt" }, contenido: { es: "1️⃣ Elige tus números: haz clic en los numeritos de la mesa\n2️⃣ O elige más rápido: presiona Col 1/2/3 o ROJO/NEGRO\n3️⃣ ¿Quieres cambiar? Haz clic en los números que NO quieras\n4️⃣ Mueve la palanquita para escoger tu apuesta\n5️⃣ ¡Presiona GIRAR o la tecla Enter y cruza los dedos! 🤞", en: "1️⃣ Pick your numbers: click the numbers on the table\n2️⃣ Or go faster: press Col 1/2/3 or RED/BLACK\n3️⃣ Want to change? Click the numbers you DON'T want\n4️⃣ Move the slider to choose your bet\n5️⃣ Press SPIN or the Enter key and cross your fingers! 🤞", ru: "1️⃣ Выберите свои числа: нажмите на числа на столе\\n2️⃣ Или быстрее: нажмите Кол. 1/2/3 или КРАСНЫЙ/ЧЁРНЫЙ\\n3️⃣ Хотите изменить? Нажмите на числа, которые НЕ хотите\\n4️⃣ Передвиньте ползунок, чтобы выбрать ставку\\n5️⃣ Нажмите КРУТИТЬ или клавишу Enter и скрестите пальцы! 🤞", ja: "1️⃣ 数字を選ぶ：テーブルの数字をクリック\\n2️⃣ もっと早く選ぶ：Col 1/2/3 または赤/黒を押す\\n3️⃣ 変更したい？いらない数字をクリックして外す\\n4️⃣ スライダーを動かしてベット額を選ぶ\\n5️⃣ 「回す」またはEnterキーを押して指を交差させよう！🤞", zh: "1️⃣ 选择你的数字：点击桌面上的数字\\n2️⃣ 或者更快捷：按下第1/2/3列 或 红/黑\\n3️⃣ 想更改？点击你不想要的数字取消\\n4️⃣ 移动滑块选择你的赌注\\n5️⃣ 按下“旋转”或Enter键，祈祷好运吧！🤞", de: "1️⃣ Wähle deine Zahlen: klicke auf die Zahlen am Tisch\\n2️⃣ Oder schneller: drücke Kol. 1/2/3 oder ROT/SCHWARZ\\n3️⃣ Willst du etwas ändern? Klicke auf die Zahlen, die du NICHT willst\\n4️⃣ Bewege den Schieberegler, um deinen Einsatz zu wählen\\n5️⃣ Drücke DREHEN oder die Enter-Taste und drück die Daumen! 🤞" }, icono: "🎮" },
      { titulo: { es: "🌟 Truco: Columnas y Colores", en: "🌟 Pro Tip: Columns & Colors", ru: "🌟 Хитрость: колонки и цвета", ja: "🌟 コツ：列と色", zh: "🌟 小技巧：列和颜色", de: "🌟 Trick: Kolonnen und Farben" }, contenido: { es: "Cuando eliges una columna o color, se marcan TODOS sus números solitos. ¡Luego puedes quitar los que no quieras! Así es más rápido jugar. Mira el contador para saber cuántos números llevas marcados.", en: "When you pick a column or color, ALL its numbers get selected by magic! Then you can remove the ones you don't want. It's a faster way to play! Check the counter to see how many numbers you picked.", ru: "Когда вы выбираете колонку или цвет, отмечаются ВСЕ соответствующие числа автоматически. Затем можно убрать те, что не нужны! Так играть быстрее. Проверьте счётчик, чтобы узнать, сколько чисел отмечено.", ja: "列や色を選ぶと、それに含まれる数字がすべて自動で選択されます！その後、不要な数字を外すこともできます。これでもっと速くプレイできます。カウンターで選択した数字の数を確認しましょう。", zh: "当你选择一列或一种颜色时，其所有对应的数字会自动被选中！之后你可以取消不想要的数字。这样玩起来更快。查看计数器可以知道你选中了多少个数字。", de: "Wenn du eine Kolonne oder Farbe wählst, werden ALLE zugehörigen Zahlen automatisch markiert! Danach kannst du die entfernen, die du nicht willst. So geht das Spielen schneller. Schau auf den Zähler, um zu sehen, wie viele Zahlen du markiert hast." }, icono: "🌟" },
      { titulo: { es: "📏 La Apuesta Mínima", en: "📏 Minimum Bet", ru: "📏 Минимальная ставка", ja: "📏 最低ベット額", zh: "📏 最低赌注", de: "📏 Der Mindesteinsatz" }, contenido: { es: "Cada número que marcas cuesta 2 moneditas. Entre más números, más moneditas necesitas.\n1 número → mínimo 6 monedas\n6 números → mínimo 12 monedas\n12 números (columna) → mínimo 24 monedas\n18 números (color) → mínimo 36 monedas\n¡Elige bien cuántos números quieres!", en: "Each number you mark costs 2 coins. The more numbers, the more coins you need.\n1 number → minimum 6 coins\n6 numbers → minimum 12 coins\n12 numbers (column) → minimum 24 coins\n18 numbers (color) → minimum 36 coins\nChoose your numbers wisely!", ru: "Каждое отмеченное число стоит 2 монеты. Чем больше чисел, тем больше монет нужно.\\n1 число → минимум 6 монет\\n6 чисел → минимум 12 монет\\n12 чисел (колонка) → минимум 24 монеты\\n18 чисел (цвет) → минимум 36 монет\\nВыбирайте числа с умом!", ja: "選んだ数字1つにつき2コインかかります。数字が多いほど多くのコインが必要です。\\n1つの数字 → 最低6コイン\\n6つの数字 → 最低12コイン\\n12の数字（列） → 最低24コイン\\n18の数字（色） → 最低36コイン\\n数字は賢く選びましょう！", zh: "你标记的每个数字都需要花费2枚金币。数字越多，需要的金币也越多。\\n1个数字 → 最低6枚金币\\n6个数字 → 最低12枚金币\\n12个数字（一列） → 最低24枚金币\\n18个数字（一色） → 最低36枚金币\\n请明智地选择数字数量！", de: "Jede markierte Zahl kostet 2 Münzen. Je mehr Zahlen, desto mehr Münzen brauchst du.\\n1 Zahl → mindestens 6 Münzen\\n6 Zahlen → mindestens 12 Münzen\\n12 Zahlen (Kolonne) → mindestens 24 Münzen\\n18 Zahlen (Farbe) → mindestens 36 Münzen\\nWähle deine Zahlen mit Bedacht!" }, icono: "📏" },
      { titulo: { es: "🎡 A girar", en: "🎡 Let's spin", ru: "🎡 A girar", ja: "🎡 回してみよう", zh: "🎡 开始旋转", de: "🎡 Ab geht's" }, contenido: { es: "Cuando estés listo, presiona el botón rojo GIRAR o la tecla Enter. ¡La ruleta da vueltas y vueltas... y si le atinas, GANASTE! 🎉", en: "When you're ready, press the red SPIN button or the Enter key. The wheel spins round and round... and if you guessed right, YOU WIN! 🎉", ru: "Когда будете готовы, нажмите красную кнопку КРУТИТЬ или клавишу Enter. Рулетка крутится и крутится... и если вы угадали, ВЫ ВЫИГРАЛИ! 🎉", ja: "準備ができたら、赤い「回す」ボタンかEnterキーを押しましょう。ルーレットがぐるぐる回って……当たれば勝利です！🎉", zh: "准备好后，点击红色的“旋转”按钮或按Enter键。轮盘转啊转……如果你猜中了，你就赢了！🎉", de: "Wenn du bereit bist, drücke den roten DREHEN-Button oder die Enter-Taste. Das Rad dreht sich und dreht sich... und wenn du richtig geraten hast, GEWINNST DU! 🎉" }, icono: "🎡" }
    ]
  },
  "casinoroyale": {
    titulo: { es: "Jackpot de Dados - Cómo jugar", en: "Dice Jackpot - How to play", ru: "Джекпот костей — как играть", ja: "サイコロジャックポット - 遊び方", zh: "骰子累积奖池 - 玩法", de: "Würfel-Jackpot - Spielanleitung" },
    secciones: [
      { titulo: { es: "Objetivo", en: "Goal", ru: "Цель", ja: "目的", zh: "目标", de: "Ziel" }, contenido: { es: "Lanza 2 dados y consigue combinaciones ganadoras: pares, números seguidos o los dos pares.", en: "Roll 2 dice and get winning combinations: pairs, consecutive numbers or both even.", ru: "Бросьте 2 кубика и соберите выигрышные комбинации: пары, последовательные числа или два чётных.", ja: "2つのサイコロを振って、ペア、連続した数字、両方偶数のいずれかの勝利コンビネーションを狙いましょう。", zh: "掷出2颗骰子，凑成获胜组合：对子、连续数字或两个都是偶数。", de: "Würfle mit 2 Würfeln und erziele Gewinnkombinationen: Paare, aufeinanderfolgende Zahlen oder zwei gerade Zahlen." }, icono: "🎯" },
      { titulo: { es: "Apuesta", en: "Bet", ru: "Ставка", ja: "ベット", zh: "赌注", de: "Einsatz" }, contenido: { es: "Elige tu apuesta (mínimo 10, máximo 500 monedas).", en: "Choose your bet (minimum 10, maximum 500 coins).", ru: "Выберите свою ставку (минимум 10, максимум 500 монет).", ja: "ベット額を選びましょう（最低10、最高500コイン）。", zh: "选择你的赌注（最低10枚，最高500枚金币）。", de: "Wähle deinen Einsatz (mindestens 10, maximal 500 Münzen)." }, icono: "💰" },
      { titulo: { es: "Combinaciones", en: "Combinations", ru: "Комбинации", ja: "組み合わせ", zh: "组合方式", de: "Kombinationen" }, contenido: { es: "Pares (iguales): x4 de tu apuesta.\nSecuencia (ej: 3-4): x3 de tu apuesta.\nAmbos pares: x2 de tu apuesta.", en: "Pairs (equal): x4 your bet.\nSequence (e.g. 3-4): x3 your bet.\nBoth even: x2 your bet.", ru: "Пары (одинаковые): x4 вашей ставки.\\nПоследовательность (напр. 3-4): x3 вашей ставки.\\nОба чётные: x2 вашей ставки.", ja: "ペア（同じ数字）：ベット額のx4。\\n連続（例：3-4）：ベット額のx3。\\n両方偶数：ベット額のx2。", zh: "对子（相同数字）：赌注的x4倍。\\n连续数字（例如：3-4）：赌注的x3倍。\\n两个偶数：赌注的x2倍。", de: "Paare (gleich): das x4-fache deines Einsatzes.\\nFolge (z. B. 3-4): das x3-fache deines Einsatzes.\\nBeide gerade: das x2-fache deines Einsatzes." }, icono: "🏆" },
      { titulo: { es: "Cómo jugar", en: "How to play", ru: "Как играть", ja: "遊び方", zh: "玩法", de: "Spielanleitung" }, contenido: { es: "Presiona APOSTAR para lanzar los dados.", en: "Press BET to roll the dice.", ru: "Нажмите СТАВКА, чтобы бросить кости.", ja: "「ベット」を押してサイコロを振りましょう。", zh: "点击“下注”来掷骰子。", de: "Drücke WETTEN, um die Würfel zu werfen." }, icono: "🎲" }
    ]
  },
  "balatro": {
    titulo: { es: "Cartas Retro - Póker de Cartas", en: "Retro Cards - Card Poker", ru: "Ретро карты — покер на картах", ja: "レトロカード - カードポーカー", zh: "复古纸牌 - 扑克牌局", de: "Retro-Karten - Karten-Poker" },
    secciones: [
      { titulo: { es: "Objetivo", en: "Goal", ru: "Цель", ja: "目的", zh: "目标", de: "Ziel" }, contenido: { es: "Consigue la mejor mano de póker posible con 5 cartas. Gana según la jerarquía de la mano.", en: "Get the best possible poker hand with 5 cards. Win according to hand ranking.", ru: "Соберите наилучшую возможную покерную комбинацию из 5 карт. Побеждайте согласно рангу комбинации.", ja: "5枚のカードで可能な限り最高のポーカーハンドを作りましょう。役の強さに応じて勝利します。", zh: "用5张牌组成尽可能最强的扑克牌型，根据牌型等级获胜。", de: "Bilde das bestmögliche Pokerblatt mit 5 Karten. Gewinne entsprechend der Blattwertung." }, icono: "🎯" },
      { titulo: { es: "Apuesta", en: "Bet", ru: "Ставка", ja: "ベット", zh: "赌注", de: "Einsatz" }, contenido: { es: "Usa el slider para elegir tu apuesta (mínimo 10, máximo 500 monedas).", en: "Use the slider to choose your bet (minimum 10, maximum 500 coins).", ru: "Используйте ползунок, чтобы выбрать ставку (минимум 10, максимум 500 монет).", ja: "スライダーを使ってベット額を選びましょう（最低10、最高500コイン）。", zh: "使用滑块选择你的赌注（最低10枚，最高500枚金币）。", de: "Nutze den Schieberegler, um deinen Einsatz zu wählen (mindestens 10, maximal 500 Münzen)." }, icono: "💰" },
      { titulo: { es: "Manos y Premios", en: "Hands & Prizes", ru: "Комбинации и призы", ja: "役と賞金", zh: "牌型与奖励", de: "Blätter und Preise" }, contenido: { es: "Escalera Real: x70\nEscalera Color: x40\nPóker: x18\nFull House: x7\nColor: x5\nEscalera: x3\nTrío: x2\nDoble Par: x1\nPar o menos: pierdes la apuesta", en: "Royal Flush: x70\nStraight Flush: x40\nFour of a Kind: x18\nFull House: x7\nFlush: x5\nStraight: x3\nThree of a Kind: x2\nTwo Pair: x1\nPair or less: you lose your bet", ru: "Роял-флеш: x70\\nСтрит-флеш: x40\\nКаре: x18\\nФулл-хаус: x7\\nФлеш: x5\\nСтрит: x3\\nТройка: x2\\nДве пары: x1\\nПара или меньше: вы теряете ставку", ja: "ロイヤルフラッシュ：x70\\nストレートフラッシュ：x40\\nフォーカード：x18\\nフルハウス：x7\\nフラッシュ：x5\\nストレート：x3\\nスリーカード：x2\\nツーペア：x1\\nワンペア以下：ベットを失う", zh: "皇家同花顺：x70\\n同花顺：x40\\n四条：x18\\n葫芦：x7\\n同花：x5\\n顺子：x3\\n三条：x2\\n两对：x1\\n一对或更低：你将失去赌注", de: "Royal Flush: x70\\nStraight Flush: x40\\nVierling: x18\\nFull House: x7\\nFlush: x5\\nStraße: x3\\nDrilling: x2\\nZwei Paare: x1\\nPaar oder weniger: du verlierst deinen Einsatz" }, icono: "🏆" },
      { titulo: { es: "Comodines", en: "Jokers", ru: "Джокеры", ja: "ジョーカー", zh: "百搭牌", de: "Joker" }, contenido: { es: "Los comodines son cartas especiales que pueden actuar como cualquier carta para completar tu mano. ¡Aparecen aleatoriamente en el mazo!", en: "Jokers are special cards that can act as any card to complete your hand. They appear randomly in the deck!", ru: "Джокеры — это специальные карты, которые могут заменить любую карту, чтобы завершить вашу комбинацию. Они появляются случайным образом в колоде!", ja: "ジョーカーは、あなたの役を完成させるためにどんなカードにもなれる特別なカードです。デッキにランダムに出現します！", zh: "百搭牌是特殊的卡牌，可以代替任意一张牌来凑成你的牌型。它们会随机出现在牌堆中！", de: "Joker sind besondere Karten, die als jede beliebige Karte fungieren können, um dein Blatt zu vervollständigen. Sie erscheinen zufällig im Kartenstapel!" }, icono: "🃏" },
      { titulo: { es: "Nuevos Palos", en: "New Suits", ru: "Новые масти", ja: "新しいスート", zh: "新花色", de: "Neue Farben" }, contenido: { es: "Además de los 4 palos clásicos (♠♥♣♦), ahora hay 2 más: ⚜ y ☘. ¡Más chances de hacer color!", en: "In addition to the 4 classic suits (♠♥♣♦), there are 2 new ones: ⚜ and ☘. More chances for a flush!", ru: "Помимо 4 классических мастей (♠♥♣♦), теперь есть ещё 2: ⚜ и ☘. Больше шансов собрать флеш!", ja: "従来の4つのスート（♠♥♣♦）に加えて、新たに⚜と☘の2つが登場！フラッシュのチャンスが広がります！", zh: "除了4种经典花色（♠♥♣♦），现在还新增了2种：⚜和☘。让你有更多机会凑成同花！", de: "Zusätzlich zu den 4 klassischen Farben (♠♥♣♦) gibt es jetzt 2 neue: ⚜ und ☘. Mehr Chancen auf einen Flush!" }, icono: "✨" }
    ]
  },
  "duelodados": {
    titulo: { es: "Duelo de Dados - Cómo jugar", en: "Dice Duel - How to play", ru: "Дуэль на костях — как играть", ja: "サイコロ対決 - 遊び方", zh: "骰子对决 - 玩法", de: "Würfelduell - Spielanleitung" },
    secciones: [
      { titulo: { es: "Objetivo", en: "Goal", ru: "Цель", ja: "目的", zh: "目标", de: "Ziel" }, contenido: { es: "Gana 2 rondas antes que la máquina. El primero en llegar a 2 puntos gana el duelo y el premio.", en: "Win 2 rounds before the machine does. First to 2 points wins the duel and the prize.", ru: "Выиграйте 2 раунда раньше машины. Первый, кто наберёт 2 очка, выигрывает дуэль и приз.", ja: "マシンより先に2ラウンド勝利しましょう。先に2ポイント獲得した方がデュエルと賞金を獲得します。", zh: "在机器之前赢得2局。率先获得2分的一方将赢得对决和奖励。", de: "Gewinne 2 Runden vor der Maschine. Wer zuerst 2 Punkte erreicht, gewinnt das Duell und den Preis." }, icono: "🎯" },
      { titulo: { es: "Sistema de Jefes", en: "Boss System", ru: "Система боссов", ja: "ボスシステム", zh: "首领系统", de: "Boss-System" }, contenido: { es: "Hay 5 jefes con dificultad creciente:\n🟢 Novato: empate = tú ganas\n🔵 Soldado: 1d6 normal\n🟠 Élite: +1 para la máquina\n🔴 Campeón: +2 para la máquina\n👑 Rey Dado: +3 para la máquina", en: "There are 5 bosses with increasing difficulty:\n🟢 Rookie: tie = you win\n🔵 Soldier: normal 1d6\n🟠 Elite: +1 for the machine\n🔴 Champion: +2 for the machine\n👑 Dice King: +3 for the machine", ru: "Есть 5 боссов с возрастающей сложностью:\\n🟢 Новичок: ничья = вы побеждаете\\n🔵 Солдат: обычный 1d6\\n🟠 Элита: +1 машине\\n🔴 Чемпион: +2 машине\\n👑 Король Костей: +3 машине", ja: "難易度が上がる5人のボスがいます：\\n🟢 新兵：引き分け＝あなたの勝ち\\n🔵 兵士：通常の1d6\\n🟠 エリート：マシンに+1\\n🔴 チャンピオン：マシンに+2\\n👑 サイコロの王：マシンに+3", zh: "共有5个难度递增的首领：\\n🟢 新手：平局＝你获胜\\n🔵 士兵：普通1d6\\n🟠 精英：机器+1\\n🔴 冠军：机器+2\\n👑 骰子之王：机器+3", de: "Es gibt 5 Bosse mit steigendem Schwierigkeitsgrad:\\n🟢 Anfänger: Unentschieden = du gewinnst\\n🔵 Soldat: normaler 1W6\\n🟠 Elite: +1 für die Maschine\\n🔴 Champion: +2 für die Maschine\\n👑 Würfelkönig: +3 für die Maschine" }, icono: "👹" },
      { titulo: { es: "Cómo jugar", en: "How to play", ru: "Как играть", ja: "遊び方", zh: "玩法", de: "Spielanleitung" }, contenido: { es: "1. Elige tu apuesta (mínimo 6, máximo 500).\n2. Presiona LANZAR DADOS.\n3. Gana rondas para avanzar de jefe.\n4. Derrota a los 5 jefes para completar el juego.", en: "1. Choose your bet (min 6, max 500).\n2. Press ROLL DICE.\n3. Win rounds to advance to the next boss.\n4. Defeat all 5 bosses to complete the game.", ru: "1. Выберите свою ставку (минимум 6, максимум 500).\\n2. Нажмите БРОСИТЬ КОСТИ.\\n3. Выигрывайте раунды, чтобы перейти к следующему боссу.\\n4. Победите всех 5 боссов, чтобы завершить игру.", ja: "1. ベット額を選ぶ（最低6、最高500）。\\n2. 「サイコロを振る」を押す。\\n3. ラウンドに勝って次のボスに進む。\\n4. 5人のボス全員を倒してゲームクリア。", zh: "1. 选择你的赌注（最低6，最高500）。\\n2. 点击“掷骰子”。\\n3. 赢得回合以晋级挑战下一个首领。\\n4. 击败所有5个首领即可通关。", de: "1. Wähle deinen Einsatz (mindestens 6, maximal 500).\\n2. Drücke WÜRFELN.\\n3. Gewinne Runden, um zum nächsten Boss aufzusteigen.\\n4. Besiege alle 5 Bosse, um das Spiel abzuschließen." }, icono: "🎲" },
      { titulo: { es: "Premio", en: "Prize", ru: "Приз", ja: "報酬", zh: "奖励", de: "Preis" }, contenido: { es: "Ganas el doble de tu apuesta al derrotar a un jefe. A mayor apuesta, mayor premio.", en: "You win double your bet when defeating a boss. Higher bet means bigger prize.", ru: "Вы выигрываете удвоенную ставку при победе над боссом. Чем больше ставка, тем больше приз.", ja: "ボスを倒すとベット額の2倍を獲得できます。ベット額が高いほど賞金も大きくなります。", zh: "击败首领即可赢得双倍赌注。赌注越高，奖励越丰厚。", de: "Du gewinnst das Doppelte deines Einsatzes, wenn du einen Boss besiegst. Höherer Einsatz bedeutet größeren Preis." }, icono: "💰" }
    ]
  }
};

function getCurrentPage() {
  const path = window.location.pathname;
  if (path.includes("principalpage") || path.endsWith("/Let_s go Catbling 2026 - copia (2)/")) return "principalpage";
  if (path.includes("juegosprincipalpage")) return "juegos";
  if (path.includes("preguntasinicialpage")) return "preguntas";
  if (path.includes("tienda")) return "tienda";
  if (path.includes("tragamonedaindex") || path.includes("tragamonedas")) return "tragamonedas";
  if (path.includes("memoria")) return "memoria";
  if (path.includes("ruleta")) return "ruleta";
  if (path.includes("casinoroyale")) return "casinoroyale";
  if (path.includes("balatro")) return "balatro";
  if (path.includes("dadosindex")) return "duelodados";
  return "principalpage";
}

function openHelp() {
  const page = getCurrentPage();
  const data = HELP_DATA[page];
  if (!data) return;

  const lang = typeof config !== 'undefined' && config.idioma ? config.idioma : 'es';

  let overlay = document.getElementById("help-overlay");
  if (!overlay) {
    overlay = document.createElement("div");
    overlay.id = "help-overlay";
    document.body.appendChild(overlay);
  }

  const closeSrc = getBasePath() + "resources/assets/exit.png";
  const titulo = typeof data.titulo === 'object' ? (data.titulo[lang] || data.titulo.es) : data.titulo;
  let html = '<div class="help-content"><img src="' + closeSrc + '" class="help-close" id="help-close"><h2 class="help-title">' + titulo + '</h2><div class="help-secciones">';

  data.secciones.forEach(function(s) {
    const stitulo = typeof s.titulo === 'object' ? (s.titulo[lang] || s.titulo.es) : s.titulo;
    const scontenido = typeof s.contenido === 'object' ? (s.contenido[lang] || s.contenido.es) : s.contenido;
    html += '<div class="help-seccion"><div class="help-seccion-header"><span class="help-icono">' + s.icono + '</span><h3>' + stitulo + '</h3></div><p class="help-texto">' + scontenido.replace(/\n/g, "<br>") + '</p></div>';
  });

  html += '</div></div>';
  overlay.innerHTML = html;
  overlay.classList.add("active");

  document.getElementById("help-close").onclick = function() { closeHelp(); };
  overlay.onclick = function(e) { if (e.target === overlay) closeHelp(); };
  document.addEventListener("keydown", helpKeyHandler);
}

function closeHelp() {
  const overlay = document.getElementById("help-overlay");
  if (overlay) overlay.classList.remove("active");
  document.removeEventListener("keydown", helpKeyHandler);
}

function helpKeyHandler(e) {
  if (e.key === "Escape") closeHelp();
}

function getBasePath() {
  const path = window.location.pathname;
  if (path.includes("/tienda/") || path.includes("/preguntas/") || (path.includes("/juegos/") && !path.includes("/memoria/") && !path.includes("/ruleta/") && !path.includes("/tragamonedasm/") && !path.includes("/casinoroyale/") && !path.includes("/balatro/") && !path.includes("/dados/"))) return "../";
  if (path.includes("/memoria/") || path.includes("/ruleta/") || path.includes("/tragamonedasm/") || path.includes("/casinoroyale/") || path.includes("/balatro/") || path.includes("/dados/")) return "../../";
  return "./";
}

function initHelpButton() {
  const page = getCurrentPage();
  const soloJuegos = ["tragamonedas", "memoria", "ruleta", "casinoroyale", "preguntas", "balatro", "duelodados"];
  if (!soloJuegos.includes(page)) return;
  if (document.getElementById("btn-ayuda")) return;
  const btn = document.createElement("div");
  btn.id = "btn-ayuda";
  btn.textContent = "?";
  btn.onclick = openHelp;
  document.body.appendChild(btn);
}

document.addEventListener("DOMContentLoaded", function() {
  // setTimeout(initHelpButton, 300);
});

// Si el usuario cambia de idioma con la ayuda ya abierta, se refresca su
// contenido sin necesidad de cerrarla y volver a abrirla.
window.addEventListener("idiomaAplicado", function() {
  const overlay = document.getElementById("help-overlay");
  if (overlay && overlay.classList.contains("active")) {
    openHelp();
  }
});
