-- ============================================================
-- 007_add_carreras_a_casino_juego_enum.sql
--
-- BUG REAL encontrado en el Supabase real de este proyecto (no en un
-- mock): el enum casino_juego NO incluía el valor 'carreras', aunque
-- config-carrera.js (JUEGO_ID_CASINO = 'carreras') y la migración
-- 006_carreras_apuesta_puesto_segura.sql ya dan por hecho que existe.
--
-- Efecto real confirmado contra el Supabase real: CUALQUIER llamada a
--   - registrar_sesion_casino('carreras', ...)   (apuesta SIMPLE)
--   - el INSERT en sesiones_casino dentro de
--     liquidar_apuesta_puesto_carrera             (apuesta por PUESTO)
-- fallaba con "invalid input value for enum casino_juego: carreras".
--
-- Cambio puramente aditivo: no se toca ningún valor existente del enum
-- ni ninguna fila ya guardada.
-- ============================================================
ALTER TYPE casino_juego ADD VALUE IF NOT EXISTS 'carreras';
